### ISSUE TITLE
TL-WDR4900 (and likely other old dual-band routers)

### ISSUE THREAD

**Issue by mdagbro** [ericpignet/home-assistant-tplink_router#10]
Hi! I've edited the OriginalTPLinkDeviceScanner to work with dual band routers. It did work already for 2.4 GHz devices, but devices connected to the 5GHz SSID could not be tracked since they are on another url. 

Not sure if this breaks support for single band routers though. 

```
class OriginalTplinkDeviceScanner(TplinkDeviceScanner):
    """This class queries a wireless router running TP-Link firmware.
    Oldest firmware supported by this integration."""

    def _update_info(self):
        """Ensure the information from the TP-Link router is up to date.
        Return boolean if scanning successful.
        """
        _LOGGER.info("[Original] Loading wireless clients...")

        url = 'http://{}/userRpm/WlanStationRpm.htm'.format(self.host)
        referer = 'http://{}'.format(self.host)
        page = requests.get(
            url, auth=(self.username, self.password),
            headers={REFERER: referer}, timeout=4)

        pagetext = page.text
        
        # Find devices on 5GHz band
        url = 'http://{}/userRpm/WlanStationRpm_5g.htm'.format(self.host)
        referer = 'http://{}'.format(self.host)
        page = requests.get(
            url, auth=(self.username, self.password),
            headers={REFERER: referer}, timeout=4)
        
        # Combine results from 2.4 GHz and 5 GHz
        pagetext = pagetext + ' ' + page.text

        result = self.parse_macs_hyphens.findall(pagetext)

        if result:
            self.last_results = [mac.replace("-", ":") for mac in result]
            return True

        return False
```

**Comment by ericpignet** [comment]
Thanks for your contribution!
What is your router model?

I don't think it should break single band routers, if the URL does not exist, the the HTTP request should return an error code in page.status_code which is not checked, there should not be any exception thrown, but obviously there won't be any IP in page.text.
Could you do a quick test, if you introduce a typo in your 5g URL, does it still detects the 2.4 GHz IPs without side effect?

**Comment by mdagbro** [comment]
TL-WDR4900 v1, Firmware Version 3.14.7 Build 130424

You're right, 2.4GHz detection still works fine with a typo introduced in the 5g url. I've created a pull request!
