### ISSUE TITLE
Device request: TL-WR840N

### ISSUE THREAD

**Issue by rudizl** [ericpignet/home-assistant-tplink_router#7]
Hi, I have 3 TL-WR840N- one is HOST and the other two are used as extenders. What kind of indormation will be needed to add support for this model?

Cheers

**Comment by rudizl** [comment]
After adding the integration via HACS and manual installation in configuaration.yaml everything works. It will be good fix the autodiscovery of the router. 
It shows the entity as:
source type router
latitude xxxxx
longitude xxxxx
gps accuracy 0
scanner N600TplinkDeviceScanner
Thanks

**Comment by ericpignet** [comment]
Hi Rudizl,

Good to know it works with TL-WR840N!
I've just updated the doc accordingly.
Don't worry about scanner being detected as N600TplinkDeviceScanner. TPLink is using similar firmware and web interface for multiple devices. This will have no impact at all on the behaviour of the scanner, what is important is that presence detection works.

Eric
